name: Schedule Docker Build te-dep-3.9

on:
  schedule:
    # Runs at 02:00 UTC every day
    - cron: '0 2 * * *'
  # Allow manual trigger
  workflow_dispatch:

env:
  IMG_REPO: ghcr.io/mazoea/docker-te-deps
  JOBNAME: scheduled-build-te-dep-3.9

jobs:
  trigger-ci-te-base-dep:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CI workflow for te_base_dep_3.9 branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              ref: 'te_base_dep_3.9'
            });
            console.log('Workflow triggered for te_base_dep_3.9 branch:', result.status);
